[package]
name = "advent_2015"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.23"
either = "1.8.0"
itertools = "0.10.5"
md5 = "0.7.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
